spring:
   data:
        elasticsearch:
            cluster-name: elasticsearch #默认为elasticsearch
            cluster-nodes: 172.16.1.202:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
            local: false
            repositories: true